use ScuolaDB;
select*from Studenti;
select Nome,Cognome,Genere FROM Studenti;
SELECT DISTINCT NOME,COGNOME FROM STUDENTI;
-- dISTINCT SERVE A TOGLIERE I DUPLICATI DA UNA TABELLA SENZA ELIMINARLI
SELECT*FROM Studenti Where StudenteID=3

SELECT
	Nome,
	Cognome,
FROM Studenti
Where studenteId

SELECT
	Nome AS 'soprannome',
	Cognome AS 'Cognome dello studente'
FROM Studenti
Where studenteId=3

--WHERE 'DOVE ' SERVERE A DEFINIRE UNA CONDIZIONE DOVE LO STUDENTEID 3 RIGA 
--AS ALIAS -AVATAR DARE UN NOME ALLA COLONNA 

SELECT*FROM Studenti

SELECT*FROM Studenti WHERE GENERE ='F';
SELECT*FROM Studenti WHERE GENERE ='M';
SELECT DISTINCT Nome, Cognome FROM Studenti WHERE GENERE ='M';
-- VOGLIO VEDERE NOME E COGNOME TUTTI MASCHI SENZA DUPLICAZIONE
SELECT DISTINCT Nome, Cognome FROM Studenti WHERE NOME LIKE 'M%';
-- OPERATORI ARIRTMETICI -